name: Check Registry
description: Check Registry
author: Apigee Registry Authors
branding:
  color: red
  icon: cloud-lightning
inputs:
  pattern:
    description: A shell command to use to generate an authorization token for the Registry.
    required: false
  enable:
    description: Todo 
    required: false
  disable:
    description: Todo 
    required: false
  filter:
    description: Todo 
    required: false
  jobs:
    description: Todo 
    required: false
  error_on:
    description: Todo
    required: false
outputs:
  report:
    description: Check Report
    value: ${{ steps.check.outputs.REPORT }}
runs:
  using: composite
  steps:
    - name: Run Registry Check
      id: check      
      shell: bash
      run: |
        REPORT=$(registry check ${{ inputs.pattern }})
        echo ${REPORT}
        echo "REPORT=${REPORT}" >> $GITHUB_OUTPUT
    - name: Generate list using Markdown
      shell: bash
      run: |
        echo "Report:" >> $GITHUB_STEP_SUMMARY
        echo "```yaml" >> $GITHUB_STEP_SUMMARY
        echo steps.check.outputs.REPORT >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
    - shell: bash
      run: echo $GITHUB_STEP_SUMMARY
    # - name: Error if problems
    #   shell: bash
    #   run: "echo ${{ steps.check.outputs.REPORT}} | grep 'problems: \\[\\]'"
    #   echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY