on: [push, pull_request]

jobs:
  test-check-and-apply:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    runs-on: ubuntu-latest
    name: Check an API locally and apply it
    env:
      registry-yaml: api.yaml
    services:
      local-registry: # will use a local SQLite3 instance
        image: ghcr.io/apigee/registry-server:main
        env:
          REGISTRY_LOGGING_LEVEL: debug
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v3
      - name: Configure a local Registry
        uses: apigee/registry/.github/actions/setup-registry@main
        with:
          name: local
          address: localhost:8080
          insecure: true
          version: ""
          project: test
      - name: Create a project on local Registry
        run: registry rpc admin create-project --project_id test
      - name: Apply yaml to the local Registry
        run: registry apply -f ${{ env.registry-yaml }}
      - name: Run check on the local Registry, stop if WARNING or above
        uses: apigee/registry/.github/actions/registry-check@main
        with:
          pattern: projects/test
          error-level: WARNING

      # No WARNINGS or ERRORS on local Registry check, continuing on...
      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/459884772743/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "registry-editor@apigee-apihub-demo.iam.gserviceaccount.com"
      - name: Set up the Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          skip_install: true
      - uses: apigee/registry/.github/actions/setup-registry@main
        with:
          name: cloud
          project: ${{ env.GCLOUD_PROJECT }}
          address: apigeeregistry.googleapis.com:443
          insecure: false
          token-source: gcloud auth print-access-token
      - name: Apply API to cloud registry
        run: registry apply -f ${{ env.registry-yaml }}
